### ISSUE TITLE
npm install fails.

### ISSUE THREAD

**Issue by ghost** [visionmedia/screenshot-app#6]
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-d"
npm ERR! cwd /home/me/Development/screenshot-app
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message canvas@0.8.3 preinstall: `node-waf configure build`
npm ERR! message `sh "-c" "node-waf configure build"` failed with 1
npm ERR! errno {}
npm info shasum 1ce1c77b9d3b8b484db5725a5c3a6d2cecaaa777
npm info shasum /home/me/.npm/mkdirp/0.0.7/package.tgz
npm info preinstall commander@0.5.2
npm info build /home/me/Development/screenshot-app/node_modules/jade/node_modules/commander
npm info linkStuff commander@0.5.2
npm info install commander@0.5.2
npm info postinstall commander@0.5.2
npm info preinstall mkdirp@0.3.0
npm info build /home/me/Development/screenshot-app/node_modules/jade/node_modules/mkdirp
npm info linkStuff mkdirp@0.3.0
npm info install mkdirp@0.3.0
npm info postinstall mkdirp@0.3.0
npm info build /home/me/Development/screenshot-app/node_modules/jade
npm info linkStuff jade@0.26.1
npm info install jade@0.26.1
npm info postinstall jade@0.26.1
npm info shasum e0fd9d564bbe20f6a7396ca87e5dfd92f302b2d0
npm info shasum /home/me/.npm/hiredis/0.1.14/package.tgz
npm info into /home/me/Development/screenshot-app/node_modules/redis hiredis@0.1.14
npm info installOne hiredis@0.1.14
npm info unbuild /home/me/Development/screenshot-app/node_modules/redis/node_modules/hiredis
npm info shasum d813568b811efbd7fb9a7d882bcbb63f38beab1f
npm info shasum /home/me/.npm/cssom/0.2.0/package.tgz
npm info into /home/me/Development/screenshot-app/node_modules/stylus growl@1.1.0
npm info into /home/me/Development/screenshot-app/node_modules/stylus mkdirp@0.0.7
npm info into /home/me/Development/screenshot-app/node_modules/stylus cssom@0.2.0
npm info installOne growl@1.1.0
npm info installOne mkdirp@0.0.7
npm info installOne cssom@0.2.0
npm info unbuild /home/me/Development/screenshot-app/node_modules/stylus/node_modules/growl
npm info unbuild /home/me/Development/screenshot-app/node_modules/stylus/node_modules/mkdirp
npm info unbuild /home/me/Development/screenshot-app/node_modules/stylus/node_modules/cssom
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/me/Development/screenshot-app/npm-debug.log
npm not ok

**Comment by MaximOrlovsky** [comment]
same thing.
even more errors.

**Comment by leecade** [comment]
+1

canvas is too old
